### ISSUE TITLE
Restrictions for identifying my model + model extension

### ISSUE THREAD

**Issue by jonasld23** [jonasld23/Jonas-Davidsen---Macroeconometrics#2]
Hi Tomasz @donotdespair,

I hope this message finds you well.

I know that I'll make you use of exclusion restrictions in order to identify my model, but I'm still in doubt how to exactly set these restrictions on my B_0 matrix. For now I'm thinking about following section 8.4.1 in Kilian & Lütkepohl and impose a recursive system on my variables. 

My y matrix is (cpi, ip, m2, ff, hp, spx)', where ip denotes industrial production, hp denotes house prices and spx is the sp500 index. Thus, I would interpret the first two equations in the u_t = B_0 w_t system as an AS/AD model with a horizontal AS curve and downward-sloping AD curve and the third equation as a money demand equation. The fourth equation would represent the monetary policy reaction function. So any change in ff not accounted for by this reaction function, I would interpret as a money supply shock, which is the shock I'm investigating in my project. Last but not least I have house prices and the sp500 index as the last two variables, meaning they are affected contemporaneously by the first 4 variables but not the other way around. 

Does this recursive system of identifying my model seem plausible in your opinion?

In regards to the extension of my model I'm thinking about estimating my hyperparameter. I don't seem to be able to find any literature or code on this. Any chance you can point me in the right direction?

Thanks a lot in advance.

Kind regards, 
Jonas

**Comment by donotdespair** [comment]
Hi @jonasld23 

Nice work with the identification of the system and scrutinising the corresponding restrictions. So, I would suggest that you estimate this recursive model using Waggoner & Zha (2003) algorithm. Let's discuss the motivation for this when we meet.

Regarding the priors, the most relevant reference will be this paper by [Joshua Chan](https://www.econometricsociety.org/publications/quantitative-economics/2022/07/01/Asymmetric-conjugate-priors-for-large-Bayesian-VARs), of course (he's good!). He assumes inverted gamma priors for the hyper-parameters of Minnesota prior. So, something exactly for you! :)

Let me know what you think.

**Comment by jonasld23** [comment]
Hi @donotdespair

Apologies for not responding to your answer above. Very helpful, thanks. 

Following up on Yobins comment regarding the change of definition of the M2 aggregate, I have now run my model with M1 instead. Please see the attached screenshots, where I compare the IRFs using M1 and M2.

M1:
![IRF M1](https://github.com/jonasld23/Jonas-Davidsen---Macroeconometrics/assets/127575064/64b1d125-0484-494b-90e1-12c494cda2b3)

M2:
![IRF M2](https://github.com/jonasld23/Jonas-Davidsen---Macroeconometrics/assets/127575064/508dcdce-f74b-41e0-adb9-2e0d94caa7eb)

I would argue that using M1 has improved the IRFs considerably. Would you agree with this?

Many thanks in advance and do not despair.

Jonas

**Comment by donotdespair** [comment]
Yes, i would :) nice work. So now, the irf of money and stocks are as they should! It's still interesting that all the irfs except for money hike. Would you compute the irfs for 5 years ahead?

**Comment by jonasld23** [comment]
Yes, I agree. But isn't it plausible that house prices, inflation and activity rises initially? Since it is an inflationary/stimulating shock? 

Please see below the IRFs for 5y ahead. It seems like stocks and industrial production converges to zero. It only has a significant long run effect on the levels of CPI and house prices. Further, the fed funds rate goes into negative territory after around 4y. Isn't this in line with theory as the fed naturally would react to rising prices and output after some time?
![5y IRF](https://github.com/jonasld23/Jonas-Davidsen---Macroeconometrics/assets/127575064/3cd99719-444b-4990-8504-8209bb353835)

@donotdespair

**Comment by donotdespair** [comment]
Hey @jonasld23 

You have to be careful with the interpretations of the IRFs. Those that you plotted are IRFs to a single cause, which is a positive shock increasing the money. Don't bring in the simultaneity of inflation and interest rate movement here. You have IRFs to other shocks that could be interpreted this way. So, please just stick to the interpretations about what the positive money supply shock does.

I'd say that all your responses look fine and would have standard interpretations. But the increase of interest rates following the inflow of new money is a bit puzzling.

**Comment by jonasld23** [comment]
Thanks for the feedback @donotdespair.

I can see that one has to be careful with the interpretations. I will stick to solely interpreting the effect of a money supply shock.

I agree that the increase of rates is odd as increased money supply should make money cheaper.

**Comment by donotdespair** [comment]
Hey @jonasld23 

Great! BTW, for future reference, [Belongia & Ireland](https://doi.org/10.1080/07350015.2014.946132)'s paper is one of the recent works that would also look at the money supply shock.

**Comment by donotdespair** [comment]
Hey @jonasld23 

The materials for the Student t error terms are not numerous. One is the appendix to a textbook by [Bauwens, Lubrano, Richards (1999)](https://mega.nz/file/vwRRzSya#hs-GrevqxlUx51ijHD9XdfSQIz_RtaWCM9hhmCGJqWs). Another is the article by [Geweke (1993)](https://doi.org/10.1002/jae.3950080504).

And the Paper Nathan found instructive to him was by [Bobeica and Hartwig](https://www.sciencedirect.com/science/article/pii/S0169207022000024)

**Comment by donotdespair** [comment]
```
tmp <- try(G.standard.deviation(aux, priors, restrictions))
 
if(!inherits(tmp, "try-error")){
                aux <- tmp
}else{
                cat(iteration,"Standard deviation error\n")
}
```

**Comment by jonasld23** [comment]
Hi @donotdespair,

Thanks for sending it through. I tried to run the model with 10k draws and it was done really quick. It also seemed like the rejection-rate we set up earlier turned out to be 100%. So something is completely off. Especially considering that it works for the artificial data. I'm unsure what to do wrt. to the final submission. Can I just say it didn't work out with my data?

Have a great weekend.

Greetings, Jonas

**Comment by jonasld23** [comment]
Hi again @donotdespair ,

I fixed the issue with my matrices not being positive definite. Thus, I'm now able to run my model without the above try function.

However, as seen below my lambda clearly doesn't converge, but rather explodes. For the artificial data it converges though. 

Artificial data:
![lambda_art](https://github.com/jonasld23/Jonas-Davidsen---Macroeconometrics/assets/127575064/24fe71cf-81e3-40cc-8b66-fcee5f6e9666)

Actual data:
![lambda_act](https://github.com/jonasld23/Jonas-Davidsen---Macroeconometrics/assets/127575064/15847de4-424a-4702-beef-d7fe8612d319)

As I unfortunately don't have much time left for finalizing my report, I will conclude that this model doesn't converge properly on my data and therefore is somewhat a failed experiment. Would that make sense?

Thanks in advance.

Jonas
